### ISSUE TITLE
Some Make trouble

### ISSUE THREAD

**Issue by polluks** [fpjohnston/TECO-64#11]
````
$ make -d
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
Reading makefiles...
Reading makefile `Makefile'...
Reading makefile `etc/make/sources.mk' (search path) (no ~ expansion)...
Reading makefile `etc/make/display.mk' (search path) (no ~ expansion)...
etc/make/display.mk:36: *** missing separator.  Stop.
````

**Comment by fpjohnston** [comment]
Line 36 in etc/make/display.mk is:

undefine option

Can you replace that with:

option =

And let me know if that fixes the problem? If so, it means that your version of make doesn't allow the use of undefine.

Thanks.

**Comment by polluks2** [comment]
Now works, teco compiled :-)
https://stackoverflow.com/questions/12215975/how-can-i-undefine-variable-in-a-makefile-via-command-line
I don't know why Apple still uses 3.81
BTW I just watching https://www.youtube.com/watch?v=IL-MMSv5S-o NCommander wants a new Make :-D

**Comment by polluks** [comment]
Now works, teco compiled :-)
````
[...]
Making page_vm.o
Making teco
ld: warning: option -s is obsolete and being ignored
````
https://stackoverflow.com/questions/12215975/how-can-i-undefine-variable-in-a-makefile-via-command-line
I don't know why Apple still uses 3.81
BTW I just watching https://www.youtube.com/watch?v=IL-MMSv5S-o NCommander wants a new Make :-D
