### ISSUE TITLE
Can't compile teco-64 under Gentoo Linux. "DSO missing"

### ISSUE THREAD

**Issue by mcctuxic** [fpjohnston/TECO-64#15]
Thank you very much for rebuilding the legend! :)

I am running Gentoo Linux.
**gcc**
gcc (Gentoo 12.3.1_p20230825 p2) 12.3.1 20230825
**glibc**
2.38-r6
**binutils**
2.41-r2
**ldd**
ldd (Gentoo 2.38-r6 (patchset 6)) 2.38

To compile teco-64 I did a 'make' in the root of the clone repo and got this error message:
```
gcc -o bin/teco @obj/objects.lis -l ncurses -Ofast -s
/usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: obj/display.o: undefined reference to symbol 'TABSIZE'
/usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: /lib64/libtinfo.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:68: bin/teco] Error 1
[1]    18699 exit 2     make
```

Beside this, the compiler suit works fine - Gentoo is a source-only distro, you need to compile everything locally.
How can I compile teco-64 successfully?

**Comment by mcctuxic** [comment]
The problem seems to be, that in this line of the makefile
```
	$(CC) -o $@ @obj/objects.lis $(LINKOPTS)
```
the variable LINKOPTS remains unset.

Adding to the line like this:
```
	$(CC) -o $@ @obj/objects.lis $(LINKOPTS)  -ltinfo
```
solves the problem for me.

**Comment by fpjohnston** [comment]
My apologies for the delay in my response. Thanks for your bug report, and for your follow-up regarding a fix. I have not had much cause to work on TECO for some months, but I will investigate this issue shortly.

**Comment by mcctuxic** [comment]
No need to apologize!!!!!!! I am very happy to have found this teco! :)

**Comment by mcctuxic** [comment]
See my previous post. There is a way for me to compile teco-64 :)
