### ISSUE TITLE
mkstemps

### ISSUE THREAD

**Issue by polluks** [fpjohnston/TECO-64#2]
This function is not POSIX and not part of my SDK.

**Comment by fpjohnston** [comment]
You are correct. I will modify the code to use *mkstemp()*, which I hope is
included in your SDK.

Franklin

**Comment by fpjohnston** [comment]
Okay, I've fixed this also. I had to use a bit more code to accomplish what
I originally did with *mkstemps()*, but I think it was worth it, as I agree
that I should stick with ANSI/POSIX functions when possible.

New code will be uploaded later today.

**Comment by polluks** [comment]
thx
